jdk-oracle:
    service:
        image: dockerfile/jdk-oracle
        name: jdk-oracle
    images:
        - ubuntu
        - jdk-oracle

redis:
    service:
        image: dockerfile/redis
        name: redis
        port:
          - 6379
    images:
        - ubuntu
        - redis

mongodb:
    service:
        image: dockerfile/mongodb
        name: mongodb
        port:
          -27017
    images:
        - ubuntu
        - mongodb

elasticsearch:
    service:
        image: dockerfile/elasticsearch
        name: elasticsearch
        port:
          - 9200
          - 9300
    images:
        - ubuntu
        - jdk-oracle
        - elasticsearch

postgres:
    service:
        image: dockerfile/postgres
        name: postgres
        port:
          - 5432
    images:
        - ubuntu
        - postgres

mariadb:
    service:
        image: dockerfile/mariadb
        name: mariadb
        port:
          - 3306
    images:
        - ubuntu
        - mariadb
